/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package misau.view.user;

import dao.ConsultaDAO;
import dao.HospitalDAO;
import dao.ServicoDAO;
import dao.UtenteDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import misau.model.Consulta;
import misau.model.Hospital;
import misau.model.Servico;
import misau.model.Utente;

/**
 *
 * @author Pedro Manjate
 */
public class Listarconsultas extends javax.swing.JPanel {

    /**
     * Creates new form Listarconsultas
     */
    
     DefaultTableModel model ;
     Border b;
     UtenteDAO o;
     ConsultaDAO dao;
     List<Consulta> consultas;
     List<Utente> utentes;
     Consulta gets;
    public Listarconsultas(Border b) throws SQLException, ClassNotFoundException {
          model = new DefaultTableModel();
        initComponents();
        this.b =b;
        dateChooser1.setTextRefernce(txData);
     
        model.addColumn("Paciente");
		model.addColumn("Servico");
		model.addColumn("Data");
		model.addColumn("Hora");;
		model.addColumn("Estado");
                
                  while (model.getRowCount() > 0) {
			model.removeRow(0);
		}
                  o = new UtenteDAO();
                  ServicoDAO aO = new ServicoDAO();
         List<Servico> readAll = aO.readAll();
                  dao = new ConsultaDAO();
                    Utente u= null;
                       Servico c = null;
                       consultas = dao.readAll();
                                        for (Consulta v : consultas) {  
                                            
                                           
                                              for (Servico servico : readAll) {
                             if(servico.getId()==v.getServicoId()) c =servico;
                           
            
        }
             utentes = o.readAll();
                                            
	                      for (Utente utente : utentes) {
                           if(utente.getId()==v.getUtenteId()) u =utente;
                       }
                               consulta.addItem(u.getNome()+" Status : "+v.getStatusConsulta());
			model.addRow(new Object[] {   u.getNome(), c.getNome(),v.getDataConsulta(),v.getHoraConsulta(),v.getStatusConsulta() });
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        consulta = new javax.swing.JComboBox<>();
        cSaude = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        hora = new javax.swing.JComboBox<>();
        pTxEmail1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        txData = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        table.setModel(model);
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, 680, -1));

        consulta.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        consulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar  Consulta" }));
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 64, 520, 50));

        cSaude.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        add(cSaude, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 150, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Nome");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 50, 46));

        lbNome.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 150, 40));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setText("Cartao De Saude ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 140, 46));

        jButton1.setBackground(new java.awt.Color(54, 165, 108));
        jButton1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Marcada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, 52));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setText("Consultas                                                                                                                                                                                                                                                                           Ussd based system ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 47));

        jButton2.setBackground(new java.awt.Color(255, 59, 39));
        jButton2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 310, 48));

        jButton3.setBackground(new java.awt.Color(47, 255, 90));
        jButton3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Marcar como Concluida");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 310, 52));

        hora.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora Da Consulta", "8:00 - 8:30", "8:30-9:00", "8:30-9:00", "9:30-10:00", "10:30-11:00", "11:30-12:00", "12:30-13:00", " ", " " }));
        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });
        add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 290, 50));

        pTxEmail1.setBorder(b);
        pTxEmail1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pTxEmail1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 50, 30));

        txData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDataActionPerformed(evt);
            }
        });
        pTxEmail1.add(txData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        add(pTxEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 290, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
          gets = consultas.get(consulta.getSelectedIndex()-1);
         for (Utente u : utentes) {
           if(u.getId()==gets.getUtenteId()) {
           cSaude.setText(u.getNumeroSaude());
           lbNome.setText(u.getNome());
           }
        }
                 
    }//GEN-LAST:event_consultaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dateChooser1.showPopup();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDataActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  gets.setStatusConsulta("Concluida");
         try {      
             dao.update(gets);
         } catch (SQLException ex) {
             Logger.getLogger(Listarconsultas.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(Listarconsultas.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             gets.setDataConsulta(txData.getText());
             gets.setHoraConsulta(hora.getSelectedItem().toString());
             gets.setStatusConsulta("Marcada");
             dao.update(gets);
         } catch (SQLException ex) {
             Logger.getLogger(Listarconsultas.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(Listarconsultas.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
     
    }//GEN-LAST:event_horaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          gets.setStatusConsulta("Cancelada");
         try {
             dao.update(gets);
         } catch (SQLException ex) {
             Logger.getLogger(Listarconsultas.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(Listarconsultas.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cSaude;
    private javax.swing.JComboBox<String> consulta;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JComboBox<String> hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JPanel pTxEmail1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txData;
    // End of variables declaration//GEN-END:variables
}
